### PR TITLE
allow polymur-gateway to bind to different port

### PR DESCRIPTION
**Pull request by russellballestrini**
allow polymur-gateway to bind to different port

### CODE REVIEW

**Comment by russellballestrini** [comment]
Fixes #43

**Comment by samlinbris** [comment]
Any chance I can have tcp2003 to listen to collectd & udp8125 to listen to statsd?

**Comment by jamiealquiza** [comment]
It's recommended to use statsd separately (possibly on the same box from which the metrics originate) and forwarding that to Polymur, since the output of statsd is graphite protocol. Polymur also lacks some of the features you might like in statsd, such as histograms or sampling, since those aren't features that Polymur focuses on.

**Comment by samlinbris** [comment]
@jamiealquiza does this means I might need multiple statsd-listener instances if I'm expecting massive traffic? StatsD keeps an active connection to polymur afaik, just a bit uncertain how much statsd-listener can handle and when to scale if needed.

**Comment by jamiealquiza** [comment]
statsd can handle quite a bit of data volume, especially if you're using one of the non-nodejs rewrites. I've used the original nodejs implementation where one runs locally on every instance in the infrastructure, and never had issues handling throughput. Thousands of these connected to two Polymur instances.

**Comment by samlinbris** [comment]
Thank you for your informative replies @jamiealquiza. I appreciate it mate

**Pull request closed without merging**
